# Server port (optional)
server.port=8081

# PostgreSQL connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/medilabo_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:medilabo_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:9188}
spring.datasource.driverClassName=org.postgresql.Driver

# JPA & Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=medilabo_user
spring.security.user.password=9188

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG