server.port=8083
spring.application.name=physician-notes

# MongoDB connection
spring.data.mongodb.uri=mongodb://localhost:27017/medilabo_notes

# Spring Security in-memory user details
spring.security.user.name=medilabo_user
spring.security.user.password=9188
