server.port=8084

gateway.url=${GATEWAY_URL:http://localhost:8080}
gateway.user=medilabo_user
gateway.password=9188

spring.security.user.name=medilabo_user
spring.security.user.password=9188

logging.level.com.medilabo.risk=DEBUG